import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ldq, LdQWeb.Endpoint,
  url: [host: "www.lecture-de-qualite.net", port: 8103],
  check_origin: ["https://www.lecture-de-qualite.net", "https://www.lecture-de-qualite.fr"],
  # url: [host: "icare.alwaysdata.net", path: "/label", port: 8103],
  http: [port: 8103],
  server: true, # ajouté par Phil
  debug_errors: true, #, # true pour voir les erreurs en production
  cache_static_manifest: "priv/static/cache_manifest.json"

config :ldq, env: :prod # pour pouvoir faire Application.get_env(:ldq, :env) 

  # Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: LdQ.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
