## Faire connaitre le label

Vous avez de nombreux moyens de faire connaitre le label var(label_ldq). Les voici :

* Parlez-en simplement autour de vous, et notamment auprès des autrices et auteurs autoédités,
* Mettez un lien vers ce site depuis votre page de profil d'autrice ou d'auteur, sur Facebook ou autre réseau social.