## Faire connaitre le label

Vous avez de nombreux moyens de faire connaitre le label var(label_ldq). Les voici :

* parlez-en simplement autour de vous, et notamment auprès des autrices et auteurs autoédités,
* parlez-en sur les réseaux sociaux d'auteurs que vous vous connaissez, et notamment les groupes d'autoédition, il y a a plétores sur Facebook,
* mettez un lien vers ce site depuis votre page de profil d'autrice ou d'auteur, sur Facebook ou autre réseau social,
* ne manquez pas de parler des derniers livres labellisés que vous avez lus